#Facebook:

# Importing the libraries




In [189]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Import the dataset

In [190]:
dataset = pd.read_csv('fbdataset.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [191]:
print(X)

[[2.30e+01 5.55e-04]
 [2.60e+01 1.20e-09]
 [2.20e+01 5.53e-02]
 [2.00e+01 1.93e-03]
 [3.30e+01 1.57e-03]
 [2.60e+01 6.73e-04]
 [3.10e+01 1.99e-02]
 [3.00e+01 8.90e-01]
 [2.20e+01 1.61e-03]
 [1.90e+01 5.29e-03]
 [2.40e+01 3.61e-03]
 [2.40e+01 1.35e-02]
 [2.50e+01 4.89e-04]
 [2.00e+01 1.80e-01]
 [2.40e+01 1.31e-03]]


#Feature scaling

In [192]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[2.86e-01 6.23e-04]
 [5.00e-01 0.00e+00]
 [2.14e-01 6.21e-02]
 [7.14e-02 2.17e-03]
 [1.00e+00 1.76e-03]
 [5.00e-01 7.56e-04]
 [8.57e-01 2.23e-02]
 [7.86e-01 1.00e+00]
 [2.14e-01 1.81e-03]
 [0.00e+00 5.94e-03]
 [3.57e-01 4.05e-03]
 [3.57e-01 1.52e-02]
 [4.29e-01 5.49e-04]
 [7.14e-02 2.02e-01]
 [3.57e-01 1.47e-03]]


#Splitting the training set and test set

In [193]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_scaled, Y, test_size = 0.2, random_state = 0)

#Training the multiple linear regression model

In [194]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

#Predicting the test results

In [195]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[3.03 3.  ]
 [2.64 1.  ]
 [3.35 1.  ]]


#Instagram:

#Import the dataset

In [196]:
igdataset = pd.read_csv('igdataset.csv')
X_ig = igdataset.iloc[:,:-1].values
Y_ig = igdataset.iloc[:,-1].values

In [197]:
print(X_ig)

[[2.80e+01 9.48e-03]
 [3.00e+01 1.84e-03]
 [5.50e+01 2.24e-03]
 [4.50e+01 4.62e-01]
 [4.70e+01 6.00e-07]
 [3.30e+01 5.87e-02]
 [3.20e+01 3.37e-01]
 [4.30e+01 2.13e-02]
 [2.40e+01 8.56e-06]
 [2.50e+01 6.66e-01]
 [6.60e+01 6.88e-04]
 [3.20e+01 7.54e-04]
 [4.60e+01 9.44e-01]
 [4.40e+01 9.65e-03]
 [3.40e+01 3.60e-01]
 [3.40e+01 1.37e-02]
 [3.10e+01 1.86e-03]
 [4.90e+01 8.64e-04]
 [2.10e+01 4.51e-01]
 [3.20e+01 1.44e-03]
 [5.00e+01 1.15e-04]
 [5.10e+01 1.83e-04]
 [4.30e+01 2.57e-04]
 [4.10e+01 4.15e-03]]


#Feature scaling

In [198]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_ig_scaled = scaler.fit_transform(X_ig)
print(X_ig_scaled)

[[1.56e-01 1.00e-02]
 [2.00e-01 1.95e-03]
 [7.56e-01 2.37e-03]
 [5.33e-01 4.89e-01]
 [5.78e-01 0.00e+00]
 [2.67e-01 6.22e-02]
 [2.44e-01 3.57e-01]
 [4.89e-01 2.26e-02]
 [6.67e-02 8.44e-06]
 [8.89e-02 7.05e-01]
 [1.00e+00 7.28e-04]
 [2.44e-01 7.98e-04]
 [5.56e-01 1.00e+00]
 [5.11e-01 1.02e-02]
 [2.89e-01 3.82e-01]
 [2.89e-01 1.45e-02]
 [2.22e-01 1.97e-03]
 [6.22e-01 9.14e-04]
 [0.00e+00 4.77e-01]
 [2.44e-01 1.53e-03]
 [6.44e-01 1.21e-04]
 [6.67e-01 1.94e-04]
 [4.89e-01 2.71e-04]
 [4.44e-01 4.40e-03]]


#Splitting the dataset into training and test set

In [199]:
from sklearn.model_selection import train_test_split
x_ig_train, x_ig_test, y_ig_train, y_ig_test = train_test_split(X_ig_scaled, Y_ig, test_size = 0.2, random_state = 0)

#Training the multiple linear regression model

In [200]:
from sklearn.linear_model import LinearRegression
regressor_ig = LinearRegression()
regressor_ig.fit(x_ig_train, y_ig_train)

LinearRegression()

#Predicting the test results

In [201]:
y_ig_pred = regressor_ig.predict(x_ig_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_ig_pred.reshape(len(y_ig_pred), 1), y_ig_test.reshape(len(y_ig_test), 1)),1))

[[25.64 65.  ]
 [60.27 11.  ]
 [36.85  5.  ]
 [19.44 11.  ]
 [43.98  4.  ]]


#Tiktok:

#Import the dataset

In [202]:
tkdataset = pd.read_csv('tkdataset.csv')
X_tk = tkdataset.iloc[:,:-1].values
Y_tk = tkdataset.iloc[:,-1].values

In [203]:
print(X_tk)

[[2.30e+01 5.33e-02]
 [2.20e+01 2.30e-01]
 [3.00e+01 1.28e-01]
 [3.30e+01 9.14e-02]
 [3.30e+01 9.14e-02]
 [2.70e+01 2.89e-04]
 [2.60e+01 1.01e-01]
 [2.50e+01 2.18e-01]
 [1.80e+01 3.13e-01]
 [3.10e+01 2.49e-03]
 [2.60e+01 5.45e-01]
 [3.40e+01 4.09e-01]
 [3.80e+01 9.39e-01]
 [3.90e+01 2.22e-04]
 [4.10e+01 2.36e-05]
 [2.70e+01 6.75e-01]
 [2.70e+01 6.75e-01]
 [2.40e+01 1.67e-02]
 [2.90e+01 5.22e-02]
 [2.20e+01 3.13e-01]
 [3.40e+01 1.00e+00]
 [2.00e+01 7.09e-01]
 [2.80e+01 9.99e-01]
 [5.50e+01 2.34e-03]
 [4.30e+01 2.38e-02]
 [2.60e+01 2.07e-01]
 [4.10e+01 3.77e-02]
 [2.80e+01 7.47e-01]
 [5.00e+01 4.99e-06]
 [2.60e+01 3.31e-03]
 [2.90e+01 2.64e-01]
 [2.80e+01 4.02e-02]
 [3.90e+01 7.51e-02]
 [3.50e+01 1.44e-02]
 [1.70e+01 3.13e-01]]


#Feature scaling

In [204]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_tk_scaled = scaler.fit_transform(X_tk)
print(X_tk_scaled)

[[1.58e-01 5.33e-02]
 [1.32e-01 2.30e-01]
 [3.42e-01 1.28e-01]
 [4.21e-01 9.14e-02]
 [4.21e-01 9.14e-02]
 [2.63e-01 2.84e-04]
 [2.37e-01 1.01e-01]
 [2.11e-01 2.18e-01]
 [2.63e-02 3.13e-01]
 [3.68e-01 2.49e-03]
 [2.37e-01 5.45e-01]
 [4.47e-01 4.09e-01]
 [5.53e-01 9.39e-01]
 [5.79e-01 2.17e-04]
 [6.32e-01 1.86e-05]
 [2.63e-01 6.75e-01]
 [2.63e-01 6.75e-01]
 [1.84e-01 1.67e-02]
 [3.16e-01 5.22e-02]
 [1.32e-01 3.13e-01]
 [4.47e-01 1.00e+00]
 [7.89e-02 7.09e-01]
 [2.89e-01 9.99e-01]
 [1.00e+00 2.33e-03]
 [6.84e-01 2.38e-02]
 [2.37e-01 2.07e-01]
 [6.32e-01 3.77e-02]
 [2.89e-01 7.47e-01]
 [8.68e-01 0.00e+00]
 [2.37e-01 3.30e-03]
 [3.16e-01 2.64e-01]
 [2.89e-01 4.02e-02]
 [5.79e-01 7.51e-02]
 [4.74e-01 1.44e-02]
 [0.00e+00 3.13e-01]]


#Splitting the dataset into training and test set

In [205]:
from sklearn.model_selection import train_test_split
x_tk_train, x_tk_test, y_tk_train, y_tk_test = train_test_split(X_tk_scaled, Y_tk, test_size = 0.2, random_state = 0)

#Training the multiple linear regression model

In [206]:
from sklearn.linear_model import LinearRegression
regressor_tk = LinearRegression()
regressor_tk.fit(x_tk_train, y_tk_train)

LinearRegression()

#Predicting the test results

In [207]:
y_tk_pred = regressor_tk.predict(x_tk_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_tk_pred.reshape(len(y_tk_pred), 1), y_tk_test.reshape(len(y_tk_test), 1)),1))

[[386.13  39.  ]
 [135.96 654.  ]
 [233.19  19.  ]
 [300.73  10.  ]
 [157.74 654.  ]
 [233.19  37.  ]
 [265.79  33.  ]]
